# Generated by Django 4.1 on 2022-11-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("describtion", models.CharField(max_length=45)),
                ("done", models.BooleanField(default=False)),
            ],
        ),
    ]
